#!/bin/bash
# Sourced from:  https://jaspervdj.be/hakyll/tutorials/github-pages-tutorial.html
git stash

git checkout source

stack exec hakyllblog clean
stack exec hakyllblog build

git fetch --all
git checkout -b master --track origin/master

cp -a _site/. .

git add -A
git commit -m "Publish."

git push origin master:master

git checkout source
git branch -D master
git stash pop
